#服务端口
server:
  port: 9001
#spring配置
spring:
  # 1. 应用配置
  application:
    name: ihrm-company # 服务名称
  # 2. 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
  # 3. jpa配置
    jpa:
    database: mysql
    show-sql: true
    open-in-view: true

logging:
  level:
    com.ihrm.company.dao: info
    com.ihrm.company.test: info