server:
  port: 9002
logging:
  level:
    com.ihrm.system.controller: debug
    com.ihrm.system.dao: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ihrm?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

#  devtools
debug: true

jwt:
  config:
    key: saas-ihrm #用户秘钥
    ttl: 360000
